export const endpointCards = [
  {
    description: 'Read the album catalog, including uploaded covers and release dates.',
    endpoint: '/api/albums',
    id: 'albums-list',
    method: 'GET',
    navLabel: 'Albums',
    route: '/albums',
    title: 'Browse albums',
  },
  {
    description: 'Create a new album entry and optionally upload its cover art.',
    endpoint: '/api/albums/add',
    id: 'albums-add',
    method: 'POST',
    navLabel: 'Add album',
    route: '/albums/add',
    title: 'Add an album',
  },
  {
    description: 'Upload a track file and attach it to an existing album.',
    endpoint: '/api/tracks/add',
    id: 'tracks-add',
    method: 'POST',
    navLabel: 'Add track',
    route: '/tracks/add',
    title: 'Add a track',
  },
  {
    description: 'Start a backend session using the current login endpoint.',
    endpoint: '/api/user/login',
    id: 'auth-login',
    method: 'POST',
    navLabel: 'Login',
    route: '/auth/login',
    title: 'Log in',
  },
  {
    description: 'Create a user and receive the JWT issued by the backend.',
    endpoint: '/api/user/signup',
    id: 'auth-signup',
    method: 'POST',
    navLabel: 'Signup',
    route: '/auth/signup',
    title: 'Create an account',
  },
  {
    description: 'Clear the backend session and local frontend auth state.',
    endpoint: '/api/user/logout',
    id: 'auth-logout',
    method: 'POST',
    navLabel: 'Logout',
    route: '/auth/logout',
    title: 'Log out',
  },
  {
    description: 'Upload an arbitrary file to the backend storage service.',
    endpoint: '/storage/upload',
    id: 'storage-upload',
    method: 'POST',
    navLabel: 'Upload',
    route: '/storage/upload',
    title: 'Upload to storage',
  },
  {
    description: 'Open a stored file by id and preview it from the frontend.',
    endpoint: '/storage/item/{id}',
    id: 'storage-item',
    method: 'GET',
    navLabel: 'Storage item',
    route: '/storage/item',
    title: 'Preview storage item',
  },
];

export const primaryNav = [
  { label: 'Home', route: '/' },
  ...endpointCards.map(({ navLabel, route }) => ({ label: navLabel, route })),
];
